name: build

on:
  push:
    branches: [ main, multiple ]
  pull_request:
    branches: [ main, multiple ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set Enviroment Variables
      run: |
        echo "IMAGE=ghcr.io/${{ github.REPOSITORY }}" >> $GITHUB_ENV
        echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: $({ github.repository_owner })
        password: ${{ secrets.GITHUB_TOKEN }} 
    - name: Build
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ env.IMAGE }}:${{ env.GIT_REF }}
          ${{ env.IMAGE }}:${{ env.GIT_SHA }}

  hassio:
    name: Hassio Addon
    needs:
      - build
    runs-on: ubuntu-latest
    # Check if branch is multiple else skip
    if: github.ref == 'refs/heads/multiple'
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: oschick/hassio-addons
          token: ${{ secrets.GH_TOKEN }}
          path: ./hassio

      - name: Update version
      # Replace version in config.json with git sha
        run: |
          # Replace version in config.json with git sha
          sed -i -e s#\"version.*#\"version\":\ \"$(echo ${{ github.sha }} | cut -c1-7)\",# ./hassio/sdm_meter_to_mqtt/config.json

      - name: Push
        run: |
          cd ./hassio
          git add .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Mirror latest sdm_meter release"
          git push